[package]
name = "aideon_mneme"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
aideon_mneme_core = { path = "../mneme_core" }
aideon_mneme_store = { path = "../mneme_store" }
